version: '3.8'

services:
  node-app:
    container_name: my-node-app
    image: portfolio-server-node
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
